### ISSUE TITLE
Zeus card boop is logged but audio doesn't play

### ISSUE THREAD

**Issue by CharlieMiab** [museuminabox/brain#117] opened 2019-07-12 15:56 UTC
Recurring issue where new boxes are updated to include the Zeus intro card, the card successfully writes and boops as it is logged in the boop log but no audio plays.

Didn't have time to SSH into the box to see if the audio was there and if it's just a permissions thing as we needed to get the box working asap for client. If we experience it again I'll be sure to do so.

**Comment by amcewen** [comment] 2019-10-30 11:19
This seems to be a duplicate of #112 (just because we can't tell the difference between Zeus and God-from-the-sea... ;-)

**Closed as completed by amcewen** 2019-10-30 11:19 UTC
Labels: bug, software, duplicate
